name: main-mode3
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: xzn92/ntr-hr-build-environment:2026-08-02
    steps:
      - name: Rust env
        run: |
          ln -s /root/.rustup ~/.rustup
      - name: Clone repos
        run: |
          git clone --recurse-submodules --depth=1 https://github.com/${{ github.repository }}
          git clone --recurse-submodules --depth=1 https://github.com/xzn/BootNTR.git
          ln -s BootNTR BootNTR-Bins
      - name: Compile NTR-HR
        run: |
          pushd ntr-hr
          MAKEFLAGS="USE_CLANG=1 USE_LTO=1" ./make.sh install
          popd
      - name: Compile BootNTR-HR
        run: |
          pushd BootNTR-Bins
          ./make.sh EXTENDEDMODE=1
          popd
      - name: Prepare node
        run: |
          source /usr/share/nvm/init-nvm.sh
          nvm install node
          echo "$(dirname $(which node))" >> "$GITHUB_PATH"
      - uses: actions/upload-artifact@v4
        with:
          name: BootNTRSelector-Mode3-PabloMK7-Banner.cia
          path: BootNTR-Bins/output/3ds-arm/BootNTRSelector-Mode3-PabloMK7-Banner.cia
          compression-level: 0
